%YAML:1.0
InitParameters:
   camera_resolution: "1"
   camera_fps: "0"
   sdk_verbose_log_file: ""
   svo_real_time_mode: "0"
   coordinate_units: "0"
   coordinate_system: "0"
   depth_mode: "0"
   depth_minimum_distance: "400.000000"
   depth_maximum_distance: "600.000000"
   camera_image_flip: "0"
   enable_right_side_measure: "0"
   camera_disable_self_calib: "0"
   sdk_verbose: "1"
   sdk_gpu_id: "-1"
   depth_stabilization: "1"
   input_type_input: "6"
   input_type_conf: "0"
   optional_settings_path: "calibration/"
   sensors_required: "0"
   enable_image_enhancement: "1"
   optional_opencv_calibration_file: ""
   open_timeout_sec: "5.000000"
   async_grab_camera_recovery: "0"
   grab_compute_capping_fps: "0.000000"
   enable_image_validity_check: "0"
